import type {Product} from "@/lib/types";

export const mockFeaturedProducts: Product[] = [
    {
        id: "1",
        name: "Nike Air Max 270",
        description: "Comfortable running shoes with Air Max technology for all-day comfort and style.",
        price: 129.99,
        category: "shoes",
        subcategory: "sneakers",
        images: ["/placeholder.svg?height=400&width=400"],
        sizes: ["7", "8", "9", "10", "11", "12"],
        colors: ["Black", "White", "Blue"],
        stock: 100,
        featured: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "2",
        name: "Adidas Ultraboost 22",
        description: "Premium running shoes with Boost midsole technology for energy return.",
        price: 189.99,
        category: "shoes",
        subcategory: "running",
        images: ["/placeholder.svg?height=400&width=400"],
        sizes: ["7", "8", "9", "10", "11", "12"],
        colors: ["Black", "White", "Gray"],
        stock: 75,
        featured: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "3",
        name: "Levi's 501 Original Jeans",
        description: "The original straight fit jeans that started it all.",
        price: 89.99,
        category: "clothing",
        subcategory: "jeans",
        images: ["/placeholder.svg?height=400&width=400"],
        sizes: ["30", "32", "34", "36", "38", "40"],
        colors: ["Blue", "Black", "Gray"],
        stock: 200,
        featured: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
    {
        id: "4",
        name: "Nike Dri-FIT T-Shirt",
        description: "Moisture-wicking t-shirt perfect for workouts and casual wear.",
        price: 24.99,
        category: "clothing",
        subcategory: "t-shirts",
        images: ["/placeholder.svg?height=400&width=400"],
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "White", "Navy", "Gray"],
        stock: 300,
        featured: true,
        created_at: new Date().toISOString(),
        updated_at: new Date().toISOString(),
    },
]